version: '3.8'
services:
  inventoryapp-postgres:
    container_name: inventoryapp-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5888:5432"
    volumes:
      - inventoryapp-postgres-volume:/var/lib/postgresql/data

volumes:
  inventoryapp-postgres-volume: